app:
    resource: '@AppBundle/Controller/'
    type: annotation
default:
    path: /
    defaults:
        _controller: AppBundle:Home:default
homepage:
    path: /home
    defaults:
        _controller: AppBundle:Home:default
contact.default:
    path: /contacts
    defaults:
        _controller: AppBundle:Contact:default
contact.delete:
    path: /contact/{contact}/delete
    defaults:
        _controller: AppBundle:Contact:delete
#contact.add:
#    path: /contact/add
#    defaults:
#        _controller: AppBundle:Contact:add
#    requirements:
contact.new:
    path: /contact/new
    defaults:
        _controller: AppBundle:Contact:new
    requirements:
contact.show:
    path: /contact/{contact}
    defaults:
        _controller: AppBundle:Contact:show
    requirements:
        contactID: '\d+'
contact.list:
    path: /contacts/{page}
    defaults:
        _controller: AppBundle:Contact:list
        page: 1
    requirements:
        page: '\d+'
security.login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login
