AppBundle\Entity\Apis:
    type: entity
    table: apis
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        contactid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: contactID
        username:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        modifieddate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
