AppBundle\Entity\Payments:
    type: entity
    table: payments
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        contactid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: contactID
        employeeid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: employeeID
        amountpaid:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
        amountreceived:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
        paymentdate:
            type: datetime
            nullable: true
        modifieddate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        paymentListid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: payment_listID
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        bankingcheckid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: bankingcheckID
    lifecycleCallbacks: {  }
