AppBundle\Entity\Permissions:
    type: entity
    table: permissions
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        contactid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: contactID
        permissionListid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: permission_listID
    lifecycleCallbacks: {  }
