AppBundle\Entity\Tclasses:
    type: entity
    table: tclasses
    uniqueConstraints:
        ID:
            columns:
                - ID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
