AppBundle\Entity\Tclubs:
    type: entity
    table: tclubs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        contactid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: contactID
        address1:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        address2:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        state:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        zip:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        active:
            type: smallint
            nullable: true
            options:
                unsigned: false
        clubtypeListid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: clubtype_listID
        modifieddate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
