AppBundle\Entity\Tcontacts:
    type: entity
    table: tcontacts
    uniqueConstraints:
        id:
            columns:
                - ID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        middlename:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        lastname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        gender:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        birthdate:
            type: datetime
            nullable: true
        address1:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        address2:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        state:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        zip:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        phone1:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        phone2:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        username:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        datecreated:
            type: datetime
            nullable: true
        modifieddate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
