AppBundle\Entity\Texpenses:
    type: entity
    table: texpenses
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        note:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        date:
            type: datetime
            nullable: true
        modifieddate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        cost:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
        vendor:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        expensecategoryListid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: expensecategory_listID
    lifecycleCallbacks: {  }
