AppBundle\Entity\Tinvoiceitems:
    type: entity
    table: tinvoiceitems
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        invoiceid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: invoiceID
    lifecycleCallbacks: {  }
